app/qa/models.py
from ..dbs import db
from sqlalchemy import Column
from ..func import get_current_time

class Question(db.Model):

    __tablename__ = 'questions'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False)
    content = db.Column(db.Text(1024), nullable=False)
    answers_count = db.Column(db.Integer, default=0)
    create_time = db.Column(db.DateTime, default=get_current_time)

    author_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    author = db.relationship('User', backref=db.backref('questions', lazy='dynamic'), uselist=False)


class Answer(db.Model):

    __tablename__ = 'answers'

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text(1024))
    comments_count = db.Column(db.Integer, default=0)
    create_time = db.Column(db.DateTime, default=get_current_time)

    author_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    author = db.relationship('User', backref=db.backref('answers', lazy='dynamic'), uselist=False)

    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'))
    question = db.relationship('Question', backref=db.backref('answers', lazy='dynamic'), uselist=False)


class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text(1024))
    create_time = db.Column(db.DateTime, default=get_current_time)

    author_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'))
    author = db.relationship('User', uselist=False)

    answer_id = db.Column(db.Integer, db.ForeignKey('answers.id'))
    answer = db.relationship('Answer', backref=db.backref('comments', lazy='dynamic'), uselist=False)

app/qa/__init__.py
# encoding: utf-8

from .views import qa

app/qa/views.py
# encoding: utf-8

from flask import Blueprint, render_template, current_app, jsonify, request, redirect, url_for
from ..user import User
from flask_login import current_user
from .models import Question, Answer, Comment
from ..dbs import db

qa = Blueprint('qa', __name__, url_prefix='')

@qa.route('/', methods=["GET"])
def index():
    return render_template('qa/index.html', current_user=current_user)


@qa.route('/question/add', methods=["GET"])
def question_add():
    return render_template("qa/ask_question.html")

@qa.route('/question', methods=['GET', 'POST'])
def question_info():
    try:
        if request.method == 'POST':
            if not current_user.is_authenticated:
                return jsonify(status='error', info='请先登陆')
            question_instance = Question.query.filter(Question.name==request.form['title']).first()
            if question_instance:
                return jsonify(status='error', info='该问题已存在')
            else:
                question_instance = Question()
                question_instance.author_id = current_user.id
                question_instance.name = request.form['title']
                question_instance.content = request.form['content']
                db.session.add(question_instance)
                db.session.commit()
                return jsonify(status='success', info='问题创建成功')
        else:
            question_list = Question.query.filter().all()
            return render_template('qa/questions.html', qss=question_list)
    except Exception as e:
        current_app.logger.error(e)
        if request.method == 'POST':
            return jsonify(status='error', info='错误')
        else:
            return redirect(url_for('qa.index'))


@qa.route('/question/<int:question_id>', methods=['GET', 'POST'])
def questions(question_id):
    try:
        if request.method == 'GET':
            question_instance = Question.query.filter(Question.id==question_id).first()
            if question_instance:
                return render_template('qa/question_detail.html', qs=question_instance)
            return redirect(url_for('qa.index'))
    except Exception as e:
        current_app.logger.error(e)
        return redirect(url_for('qa.index'))

@qa.route('/question/<int:question_id>/answer', methods=['POST'])
def add_answer(question_id):
    try:
        if not current_user.is_authenticated:
            return jsonify(status='error', info='请先登陆')
        print(question_id)
        question_instance = Question.query.filter(Question.id==question_id).first()
        print(question_instance)
        if not question_instance:
            return jsonify(status='error', info='该问题不存在')
        else:
            if request.form['rtype'] == '1':
                answer_instance = Answer()
                answer_instance.content = request.form['content']
                print(request.form['content'])
                answer_instance.author_id = current_user.id
                answer_instance.question_id = question_id
                question_instance.answers_count += 1
                db.session.add(question_instance)
                db.session.add(answer_instance)
            elif request.form['rtype'] == '2':
                answer_instance = Answer.query.filter(Answer.id==request.form['rid']).first()
                if not answer_instance:
                    return jsonify(status='error', info='错误')
                comment_instance = Comment()
                comment_instance.content = request.form['content']
                comment_instance.author_id = current_user.id
                comment_instance.answer_id = answer_instance.id
                answer_instance.comments_count += 1
                db.session.add(answer_instance)
                db.session.add(comment_instance)
            else:
                return jsonify(status='error', info='错误')
            db.session.commit()
            return jsonify(status='success', info='回复成功')
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(status='error', info='错误')

app/user/views.py
# encoding: utf-8

from flask import Blueprint, request, current_app, redirect, url_for, jsonify
from .models import User
from sqlalchemy import or_
from ..dbs import db
from flask_login import login_user, logout_user, login_required, current_user

user = Blueprint('user', __name__, url_prefix='/user')

@user.route('/signup', methods=['POST'])
def user_signup():
    try:
        user_instance = User.query.filter(or_(User.name==request.form['name'],
                                              User.email==request.form['email'])
                                          ).first()
        if user_instance:
            return jsonify(status='error', info='该用户已存在')
        else:
            user_instance = User()
            user_instance.name = request.form['name']
            user_instance.email = request.form['email']
            user_instance.set_password(request.form['password'])
            db.session.add(user_instance)
            db.session.commit()
            return jsonify(status='success', info='创建成功')
    except Exception as e:
        current_app.logger.error(e)
        return redirect(url_for('qa.index'))

@user.route('/login', methods=['POST'])
def user_login():
    try:
        user_instance = User.query.filter(User.name==request.form['name']).first()
        if user_instance:
            print(request.form['name'])
            print(request.form['password'])
            if user_instance.verify_password(request.form['password']):
                login_user(user_instance)
        return redirect(url_for('qa.index'))
    except Exception as e:
        current_app.logger.error(e)
        return redirect(url_for('qa.index'))

@user.route('/logout', methods=['GET'])
@login_required
def user_logout():
    logout_user()
    return redirect(url_for('qa.index'))

app/templates/qa/ask_question.html
{% extends "qa/base.html"%}
{% block content %}
<div class="breadcrumbs">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>提问</h1>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</div><!-- End breadcrumbs -->


<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
            <div class="page-content ask-question">
                <div class="boxedtitle page-title"><h2>提问</h2></div>
                <div class="form-style form-style-3" id="question-submit">
                    <form>
                        <div class="form-inputs clearfix">
                            <p>
                                <label class="required">问题标题<span>*</span></label>
                                <input type="text" id="question-title">
                                <span class="form-description">标题</span>
                            </p>
                        </div>
                        <div id="form-textarea">
                            <p>
                                <label class="required">问题详细<span>*</span></label>
                                <textarea id="question-details" aria-required="true" cols="58" rows="8"></textarea>
                                <span class="form-description">问题的详细描述</span>
                            </p>
                        </div>
                        <p class="form-submit">
                            <input type="button" id="publish-question" value="提交问题" class="button color small submit">
                        </p>
                    </form>
                </div>
            </div>
        </div>
        {% if current_user.is_authenticated %}
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.name }}</h3>
                    <a href="{{url_for("user.user_logout")}}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
        {% endif %}
    </div>
</section>
<div id="question-data" url="{{ url_for('qa.question_info')}}"></div>
{% endblock %}

{% block footer %}
<script src="/static/js/ask.js"></script>
{% endblock %}

app/templates/qa/base.html
<!DOCTYPE html>
<html lang="zh-Hans">
<head>
    <meta charset="UTF-8">
    <title>LuoQA</title>
    <meta name="author" content="liusong">

    <!-- 移动 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- Main Style -->
    <link rel="stylesheet" href="/static/css/style.css">
    <!-- Skins -->
    <link rel="stylesheet" href="/static/css/skins/blue.css">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="/static/css/responsive.css">
    <!-- Favicons -->
    <link rel="shortcut icon" href="/static/images/favicon.ico">

</head>
<body>
<div class="loader"><div class="loader_html"></div></div>

<div id="wrap" class="grid_1200">

    {% if not current_user.is_authenticated %}
    <div class="login-panel">
        <section class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="page-content">
                        <h2>登陆</h2>
                        <div class="form-style form-style-3">
                            <form method="post" action="{{url_for('user.user_login')}}">
                                <div class="form-inputs clearfix">
                                    <p class="login-text">
                                        <input type="text" name="name" value="Username" onfocus="if (this.value == 'Username') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Username';}">
                                        <i class="icon-user"></i>
                                    </p>
                                    <p class="login-password">
                                        <input type="password" name="password" value="Password" onfocus="if (this.value == 'Password') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Password';}">
                                        <i class="icon-lock"></i>
                                        <!-- <a href="#">Forget</a> -->
                                    </p>
                                </div>
                                <p class="form-submit login-submit">
                                    <input type="submit" value="Log in" class="button color small login-submit submit">
                                </p>
                                <!--
                                <div class="rememberme">
                                    <label><input type="checkbox" checked="checked"> Remember Me</label>
                                </div> -->
                            </form>
                        </div>
                    </div><!-- End page-content -->
                </div><!-- End col-md-6 -->
                <div class="col-md-6">
                    <div class="page-content Register">
                        <h2>注册</h2>
                        <p>注册</p>
                        <a class="button color small signup">注册</a>
                    </div><!-- End page-content -->
                </div><!-- End col-md-6 -->
            </div>
        </section>
    </div><!-- End login-panel -->
    {% endif %}


    <div id="header-top">
        <section class="container clearfix">
            <nav class="header-top-nav">
                {% if current_user.is_authenticated %}
                   <ul>
                       <li><a><i class="icon-user"></i>{{ current_user.name }}</a></li>
                   </ul>
                {% else %}
                    <ul>
                        <li><a href="login.html" id="login-panel"><i class="icon-user"></i>登陆</a></li>
                    </ul>
                {% endif %}
            </nav>
            <div class="header-search">
                <form>
                    <input type="text" value="Search here ..." onfocus="if(this.value=='Search here ...')this.value='';" onblur="if(this.value=='')this.value='Search here ...';">
                    <button type="submit" class="search-submit"></button>
                </form>
            </div>
        </section>
    </div>

    <header id="header">
        <section class="container clearfix">
            <div class="logo"><a href="index.html"><img alt="" src="/static/images/logo75.png"></a></div>
            <nav class="navigation">
                <ul>
                    <li id="nav-index"><a href="{{ url_for('qa.index') }}">首页</a>
                        <!-- <ul>
                            <li class="current_page_item"><a href="index.html"></a></li>
                        </ul> -->
                    </li>
                    <li id="nav-ask"><a href="{{ url_for('qa.question_add')}}">提问</a></li>
                    <li id="nav-question"><a href="{{ url_for('qa.question_info')}}">问题</a></li>
                </ul>
            </nav>
        </section><!-- End container -->
    </header><!-- End header -->

    {% block content %} {% endblock %}


{% if not current_user.is_authenticated %}
<div class="panel-pop" id="signup">
    <h2>注册<i class="icon-remove"></i></h2>
    <div class="form-style form-style-3">
        <form>
            <div class="form-inputs clearfix">
                <p>
                    <label class="required">用户名<span>*</span></label>
                    <input type="text" name="name" id="name">
                </p>
                <p>
                    <label class="required">邮箱<span>*</span></label>
                    <input type="email" name="email" id="email">
                </p>
                <p>
                    <label class="required">密码<span>*</span></label>
                    <input type="password" name="password" value="" id="password">
                </p>
            </div>
            <p class="form-submit">
                <input type="button" value="Signup" class="button color small submit" id="submit-button">
            </p>
        </form>
    </div>
</div><!-- End signup -->
<div id="signup-data" url="{{ url_for('user.user_signup')}}"></div>
{% endif %}

<!-- js -->
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/jquery-ui-1.10.3.custom.min.js"></script>
<script src="/static/js/jquery.easing.1.3.min.js"></script>
<script src="/static/js/html5.js"></script>
<script src="/static/js/twitter/jquery.tweet.js"></script>
<script src="/static/js/jflickrfeed.min.js"></script>
<script src="/static/js/jquery.inview.min.js"></script>
<script src="/static/js/jquery.tipsy.js"></script>
<script src="/static/js/tabs.js"></script>
<script src="/static/js/jquery.flexslider.js"></script>
<script src="/static/js/jquery.prettyPhoto.js"></script>
<script src="/static/js/jquery.carouFredSel-6.2.1-packed.js"></script>
<script src="/static/js/jquery.scrollTo.js"></script>
<script src="/static/js/jquery.nav.js"></script>
<script src="/static/js/tags.js"></script>
<script src="/static/js/jquery.bxslider.min.js"></script>
<script src="/static/js/custom.js"></script>

{% block footer %}
{% endblock %}
<!-- End js -->

</body>
</html>

app/templates/qa/index.html
{% extends "qa/base.html"%}
{% block content %}
    <div class="section-warp ask-me">
        <div class="container clearfix">
            <div class="box_icon box_warp box_no_border box_no_background" box_border="transparent" box_background="transparent" box_color="#FFF">
                <div class="row">
                    <div class="col-md-3">
                        <h2> LuoQA </h2>
                        <!--
                        <p>Duis dapibus aliquam mi, eget euismod sem scelerisque ut. Vivamus at elit quis urna adipiscing iaculis. Curabitur vitae velit in neque dictum blandit. Proin in iaculis neque.</p>
                        <div class="clearfix"></div>
                        <a class="color button dark_button medium" href="#">About Us</a>
                        <a class="color button dark_button medium" href="#">Join Now</a>-->
                    </div>
                    <div class="col-md-9">
                        <form class="form-style form-style-2">
                            <p>
                                <textarea rows="4" id="question_title" onfocus="if(this.value=='')this.value='!!!';" onblur="if(this.value=='')this.value='!!!';">!!!</textarea>
                                <i class="icon-pencil"></i>
                                <span class="color button small publish-question">提交问题</span>
                            </p>
                        </form>
                    </div>
                </div><!-- End row -->
            </div><!-- End box_icon -->
        </div><!-- End container -->
    </div><!-- End section-warp -->
</div>

{% if current_user.is_authenticated %}
<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
        </div>
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.name }}</h3>
                    <a href="{{url_for("user.user_logout")}}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
    </div>
</section>
{% endif %}
{% endblock %}

{% block footer %}
<script src="static/js/index.js"></script>
{% endblock %}

app/templates/qa/question_detail.html
{% extends "qa/base.html"%}
{% block content%}
<div class="breadcrumbs">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{qs.name}}</h1>
            </div>
            <div class="col-md-12">
                <div class="crumbs">
                    <a href="#">问题</a>
                    <span class="crumbs-span">/</span>
                    <span class="current">{{qs.name}}</span>
                </div>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</div><!-- End breadcrumbs -->

<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
            <article class="question single-question question-type-normal">
                <h2>{{ qs.name }}</h2>
                <div class="question-type-main"><i class="icon-question-sign"></i>问题</div>
                <div class="question-inner">
                    {{ qs.content }}
                </div>
            </article>
            <div class="about-author clearfix">
                    <!-- <div class="author-image"> -->
                        <!-- <a href="#" original-title="admin" class="tooltip-n"><img alt="" src="http://placehold.it/60x60/FFF/444"></a> -->
                    <!-- </div> -->
                <div class="author-bio">
                    <h4>作者:</h4>
                    <p>{{ qs.author.name }}</p>
                </div><!-- End about-author -->
            </div>
            <div id="commentlist" class="page-content">
                <div class="boxedtitle page-title"><h2>答案 ( <span class="color">{{qs.answers_count}}</span> )</h2></div>
                <ol class="commentlist clearfix">
                    {% for ans in qs.answers %}
                         <li class="comment">
                               <div class="comment-body comment-body-answered clearfix">
                                    <div class="avatar"><img alt="" src="http://placehold.it/60x60/FFF/444"></div>
                                    <div class="comment-text">
                                        <div class="author clearfix">
                                            <div class="comment-author"><a href="#">{{ ans.author.name }}</a></div>
                                            <div class="comment-meta">
                                                <div class="date"><i class="icon-time"></i> {{ans.create_time}}</div>
                                            </div>
                                            <a class="comment-reply" href="#respond" ans-id="{{ ans.id }}" id="reply-answer"><i class="icon-reply"></i>回复</a>
                                        </div>
                                        <div class="text">
                                            <p> {{ ans.content }}</p>
                                        </div>
                                    </div>
                               </div>
                               <ul class="children">
                                   {% for cm in ans.comments%}
                                    <li class="comment">
                                        <div class="comment-body comment-body-answered clearfix">
                                            <div class="avatar"><img alt="" src="http://placehold.it/60x60/FFF/444"></div>
                                            <div class="comment-text">
                                                <div class="author clearfix">
                                                    <div class="comment-author"><a href="#">{{ cm.author.name }}</a></div>
                                                    <div class="comment-meta">
                                                        <div class="date"><i class="icon-time"></i> {{cm.create_time}}</div>
                                                    </div>
                                                </div>
                                                <div class="text">
                                                    <p> {{ cm.content }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </li>
                                    {% endfor %}
                               </ul>
                         </li>
                    {% endfor %}
                </ol>
            </div>
            <div id="respond" class="comment-respond page-content clearfix">
                <div class="boxedtitle page-title"><h2>提交回复</h2></div>
                <div id="reply-info" rtype="1" rid="" qs-url="{{url_for('qa.add_answer', question_id=qs.id)}}"></div>
                    <form action="" method="post" id="commentform" class="comment-form">
                        <div id="respond-textarea">
                            <p>
                                <label class="required" for="comment">回复<span>*</span></label>
                                <textarea id="comment" name="comment" aria-required="true" cols="58" rows="8"></textarea>
                            </p>
                        </div>
                        <p class="form-submit">
                            <input name="submit" type="button" id="submit" value="提交" class="button small color">
                        </p>
                    </form>
                </div>
            </div>
        {% if current_user.is_authenticated %}
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.name }}</h3>
                    <a href="{{ url_for('user.user_logout') }}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block footer %}
<script src="/static/js/questions.js"></script>
{% endblock %}

app/templates/qa/questions.html
{% extends "qa/base.html"%}
{% block content%}
<div class="breadcrumbs">
    <section class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>问题列表</h1>
            </div>
            <div class="col-md-12">
                <div class="crumbs">
                        <span class="current">问题列表</span>
                </div>
            </div>
        </div><!-- End row -->
    </section><!-- End container -->
</div><!-- End breadcrumbs -->

<section class="container main-content">
    <div class="row">
        <div class="col-md-9">
            {% for item in qss %}
            <a href="{{ url_for('qa.questions', question_id=item.id)}}">
            <article class="question single-question question-type-normal">
                <h2>{{ item.name }}</h2>
                <div class="question-type-main"><i class="icon-question-sign"></i>问题</div>
                <div class="question-inner">
                    {{ item.content }}
                </div>
            </article>
            </a>
            {% endfor %}
        </div>
        {% if current_user.is_authenticated %}
        <aside class="col-md-3 sidebar">
            <div class="widget">
                    <h3 class="widget_title">用户名：{{ current_user.name }}</h3>
                    <a href="{{url_for('user.user_logout')}}">
                        <input type="button" value="退出登录" class="button color small">
                    </a>
            </div>
        </aside>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block footer %}
<script src="/static/js/questionlist.js"></script>
{% endblock %}